- hosts: all
  tasks:
    - name: nginx is at the latest version
      become: yes
      apt:
       name: nginx
       state: present
       update_cache: yes
    - name: start nginx
      become: yes
      service:
          name: nginx
          state: started
  
